version: '3.8'

services:
  vietnamese-tts:
    image: ghcr.io/tuananhdao/tts:latest
    ports:
      - "3001:80"
    container_name: vietnamese-tts-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    # Optional: Add volumes for persistent data if needed
    # volumes:
    #   - ./data:/app/data 