services:
  vietnamese-tts:
    build:
      context: .
      args:
        - REACT_APP_ZALO_API_KEY=${REACT_APP_ZALO_API_KEY}
    ports:
      - "3000:80"
    container_name: vietnamese-tts-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    # Optional: Add volumes for persistent data if needed
    # volumes:
    #   - ./data:/app/data 